theme: jekyll-theme-minimal
title: Filmis the APP
description: What to watch, How to watch it
logo: assets/images/filmis-logo-app.png
image: assets/images/swipe-filmis-the-app.png
image: assets/images/save-filmis-the-app.png
image: assets/images/link-filmis-the-app.png
